title:   Avinash Varma
logo: "/profile_pic.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Toronto-based Data Analyst with expertise in SQL,Power BI, Python and Tableau. Passionate about transforming complex data into clear, actionable insights that drive business results.
  <br><br><br>
  <a href="https://www.linkedin.com/in/avinash-varma-67aba390">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://www.notion.so/Portfolio-Avinash-Varma-200bd3ba8d008010a3f3f818f8a62b69">View My LinkedIn Profile</a>


  
theme: jekyll-theme-minimal   
 
