title:   Avinash Varma
logo: "/profile_pic.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  I'm a Toronto-based Data Analyst with a foundation in financial services and hospitatlity operations, recently upskilled through a Business Intelligence bootcamp. I leverage tools like SQL, Power BI, Python and Tableau to uncover insights, build dashboards, and automate reporting processes. With a strong focus on problem-solving and stakeholder collaboration, I design data solutions that drive strategic decisions and operational efficiency.
  <br><br><br>
  <a href="https://www.linkedin.com/in/avinash-varma-67aba390">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://www.notion.so/Portfolio-Avinash-Varma-200bd3ba8d008010a3f3f818f8a62b69">View My Notion Profile</a>


  
theme: jekyll-theme-minimal   
 
