title:   Avinash Varma
logo: "/profile_pic.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  I’m a Data Analyst based in Toronto with a strong foundation in Business Intelligence and over 2 years of experience delivering data-driven solutions in finance, operations, and customer-focused environments. My projects and work experience reflect a passion for uncovering actionable insights through data storytelling, visualization, and analytics.

🔍 I specialize in:

SQL & Python for data wrangling, transformation, and analysis
Power BI & Tableau for building interactive dashboards and KPI tracking
Data Modeling & Visualization to support business decision-making
Communicating complex data insights to non-technical stakeholders
💼 Previously, I worked in the financial services sector (TD, RBC) and hospitality operations, where I leveraged analytics to drive customer retention, process improvements, and revenue growth.

📊 On this GitHub, you'll find projects that explore:

Sales performance analysis and dashboarding
Customer behavior segmentation using real-world datasets
Credit risk reporting automation
ETL pipelines and data storytelling with visual tools
Let’s connect! I'm actively seeking Data Analyst opportunities in Toronto.
  <br><br><br>
  <a href="https://www.linkedin.com/in/avinash-varma-67aba390">View My LinkedIn Profile</a>




  
theme: jekyll-theme-minimal   
 
