title:   Avinash Varma
logo: "/profile_pic.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Result-driven Data Analyst with a strong foundation in Business Intelligence and over 2 years of hands-on experience in data driven projects. Proven expertise in SQL, Python, Power BI and Tableau with the ability to clean,analyze and visualize complex dataset to support data-driven business desisions. Former financial services and operations professional, experienced in applying data solutions in fast-paced, customer-focused environment.
  <br><br><br>
  <a href="https://www.linkedin.com/in/avinash-varma-67aba390">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://www.notion.so/Portfolio-Avinash-Varma-200bd3ba8d008010a3f3f818f8a62b69">View My LinkedIn Profile</a>



  
theme: jekyll-theme-minimal   
 
